application: {}
environments:
  acc: {}
  dev: {}
  prod:
    allow_drop_all: 'True'
    api_path: /api
    description: ELSA Lab WP3 server
    ip: 0.0.0.0
    jwt_secret_key: bc4037d0-3841-11ee-a4cf-acde48001122
    logging:
      backup_count: 5
      datefmt: '%Y-%m-%d %H:%M:%S'
      file: wp3server.log
      format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
      level: INFO
      loggers:
      - level: warning
        name: urllib3
      - level: warning
        name: socketIO-client
      - level: warning
        name: socketio.server
      - level: warning
        name: engineio.server
      - level: warning
        name: sqlalchemy.engine
      - level: warning
        name: requests_oauthlib.oauth2_session
      max_size: 1024
      use_console: true
    port: '5000'
    uri: sqlite:///default.sqlite
  test: {}
