name: Build Algorithms

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  
  webservice:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/main/latest/g')"
        id: extract_branch
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build count algorithm
        id: docker_build_count
        uses: docker/build-push-action@v5
        with:
          context: researcher/algorithms/count
          push: true
          tags: ghcr.io/${{ env.REPO }}/count:${{ steps.extract_branch.outputs.branch }}